on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        make tests-unit
    - name: Archive test results file
      uses: actions/upload-artifact@v2
      with:
        name: unit-tests-result
        path: unit-report.html.html

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run box version
      uses: docker://echowuhao/pywright
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m playwright install
    - name: Spin webapp
      run: |
        FLASK_RUN_PORT=8080 make run &
    - name: Test with pytest
      run: |
        BASE_URL="http://localhost:8080" make tests-e2e
    - name: Archive test results file
      uses: actions/upload-artifact@v2
      with:
        name: e2e-tests-result
        path: e2e-report.html.html