on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        make tests-unit

  e2e-tests:
    runs-on: ubuntu-latest
    container:
      image: echowuhao/pywright
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install playwright
        make pw-dependencies
    - name: Test with pytest
      run: |
        make tests-unit